### ISSUE TITLE
Help changing the text 'highlight' settings

### ISSUE THREAD

**Issue by lyndhurst** [adi1090x/rofi#185]
Hi,
I am using launchers type 4, and I am modifying the style 4, but I have the same problem on all themes I tried to modify so far.

I like having feedback on item matches as I type, and I figure the list view, and/or text element 'highlight' property controls it. I understand quite well how the collection file structure works, but I have almost no experience with css (like) languages.

I tried changing fonts to make sure this was not the issue, and checked default themes to check that I have no rofi version or environment conflict. I have tried a lot of different ways and variables to get it to work, and I have no idea what else I can do. I added `highlight: bold`, and removed `highlight: none` everywhere I could think of.

These are all the modifications I have made so far with absolutely no effects. Please note that I have first tried to modify theme files directly, and decided to revert all changes, and import a modification file to keep things cleaner.
Below is the highlight modifications I want to add to several themes to get a more uniform experience. The  `background-alt` for "selected normal" text which works fine, so I think this setup is working. 

Thank you for your time, any help will be  appreciated.

```css
/* Highlight focused item background */
element selected.normal {
  background-color:            var(alternate-background);
  text-color:                  var(selected-normal-background);
}

/* Highlight entry matches as you type */
listview {
  highlight: bold;
}

element {
  highlight: bold;
}

element.highlighted {
  highlight: bold;
}

element normal.normal {
  highlight: bold;
}

element selected.normal {
  highlight: bold;
}

element alternate.normal {
  highlight: bold;
}

element-text {
  highlight: bold;
}

textbox {
  highlight: bold;
}

```

**Comment by lyndhurst** [comment]
I found the culprit if it can help someone else:

```css
configuration {
  normalize-match: true;
}
```

From the manpage:

>        -normalize-match
>       Normalize the string before matching, so o will match ö, and é matches e.
>       This is not a perfect implementation, but works.
>       For now, it disables highlighting of the matched part.
