### ISSUE TITLE
Use Multiple Fonts Scripts

### ISSUE THREAD

**Issue by MiraiMindz** [adi1090x/rofi#72]
I'm trying to change the icons of some scripts, like the `menu_apps` script, and I'm using the FontAwesome 5, I wonder if it's possible to use more than one font for icons, here is what I'm trying to do:
```css
element-text {
    font:                      "Font Awesome 5 Pro 32", "Font Awesome 5 Brands 32";
    expand:                true;
    horizontal-align:    0.5;
    vertical-align:        0;
    margin:                 0px 0px 20px 0px;
}
```
with the code above:
![image](https://user-images.githubusercontent.com/78761663/137413088-ecf2391e-5ffd-43ba-8214-1e8725ba3a4f.png)

with only `Font Awesome 5 Brands`
![image](https://user-images.githubusercontent.com/78761663/137412918-8ca3eae9-a152-402e-a475-4c91b0a1f130.png)

with only `Font Awesome 5 Pro`
![image](https://user-images.githubusercontent.com/78761663/137413119-902a62e3-6bbc-4bf7-85c9-2c4fe1dbfdaa.png)

I want to have both fonts working, how can I do it?
