### ISSUE TITLE
Icon with text below

### ISSUE THREAD

**Issue by Vietoonet** [adi1090x/rofi#9]
In the launchpad screenshot how can you display icon with text below ?

**Comment by adi1090x** [comment]
you need **rofi-git** for this to work. use following code - 

```css
element-icon {
    size:                           65px;
    border:                         0px;
}

element-text {
    expand:                         true;
    horizontal-align:               0.5;
    vertical-align:                 0.5;
    margin:                         5px 10px 0px 10px;
}
```
